### ISSUE TITLE
Error when executing a command

### ISSUE THREAD

**Issue by jmtame** [Chronophylos/rust-rcon#2]
Trying to use the example provided in the README, correct server/port/pass and command. This is what I see in the server console:

`[Rcon] Failed to parse message, incorrect format`

**Comment by Chronophylos** [comment]
What exact example are you using?

**Comment by jmtame** [comment]
I'm using the first example from the docs: `rust-rcon myrustserver.gg Kappa123 "say Setting time to 9am"`

I'm using SurvivalServers for the server, and it's using the Oxide plugin. I'm also using RustAdmin for the websocket rcon UI.

**Comment by Chronophylos** [comment]
It's working for me, but I've pushed some changes since you opened the issue. I'm working on releasing a new version.

**Comment by Chronophylos** [comment]
I've just published `v0.1.2` you can install it with `cargo install -f rust-rcon`

**Comment by jmtame** [comment]
Thanks @Chronophylos - it's working for me now!
